### ISSUE TITLE
Warning everytime autocrafter tries to craft

### ISSUE THREAD

**Issue by BasixKOR** [chibill/AutoCrafters#7] opened 2018-01-23 11:26 UTC
MC Version : 1.12.2

Plugin Version : 1.5.5

The problem? : 
```
[20:24:58 WARN]: [AutoCrafters] Task #40 for AutoCrafters v1.5.5 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Dispenser
        at minecraft16.autocrafters.Main$1.run(Main.java:139) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot-latest.jar:git-Paper-1298]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [PaperSpigot-latest.jar:git-Paper-1298]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [PaperSpigot-latest.jar:git-Paper-1298]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [PaperSpigot-latest.jar:git-Paper-1298]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-latest.jar:git-Paper-1298]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-latest.jar:git-Paper-1298]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```

What you expect to happen : crafts something

What actually happened : warned

Steps to reproduce.

1. setup a autocrafter.
2. fill output chest.

p.s. It does not work for double chests.

**Comment by BasixKOR** [comment] 2018-01-23 11:37
Or maybe infinite enchant's problem.

**Comment by wgaylord** [comment] 2018-01-23 16:59
Have you tried on a real spigot or bukkit server. I see your using PaperSpigot they do some questionable patching that has caused problems before. 

And yes that is something causing the Infinite part to cause an exception.

This is the first report of this error so I will investigate further.

**Comment by wgaylord** [comment] 2018-01-23 17:04
I will work on support for double chests as that is something I never really messed with because of the API being a bit strange about it.

**Comment by wgaylord** [comment] 2018-01-29 16:01
Sorry I can not reproduce this using Spigot or Craftbukkit. I will need more details about your set up. (As you are using a server I do not support easily because of bugs introduced.)

**Comment by BasixKOR** [comment] 2018-01-29 16:03
I will leave more infomation when possible.

**Comment by wgaylord** [comment] 2018-01-29 16:04
Thank you.

**Comment by wgaylord** [comment] 2018-02-04 18:51
Any more information? I can't really fix this for you if I don't know what you did.

**Comment by wgaylord** [comment] 2018-02-04 19:01
I will be making an update that can give more information about this error and will add the Double Chest support.

**Comment by wgaylord** [comment] 2018-02-05 05:35
Try this file and give me what it outputs. https://www.spigotmc.org/resources/autocrafters.36406/update?update=210144

**Comment by wgaylord** [comment] 2018-02-16 05:23
If you will not give anymore information I am just going to close this.

**Comment by wgaylord** [comment] 2018-05-08 04:53
This is being closed because I can't reproduce and you are unwilling to provide more information

**Closed as completed by wgaylord** 2018-05-08 04:53 UTC
Labels: bug, invalid
